// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function $$default(param) {
  return React.createElement(Link, {
              href: "/",
              children: "Home"
            });
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
