// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function $$default(req, res) {
  var message = Js_dict.get(req.query, "message");
  res.status(200).send({
        message: message !== undefined ? Caml_option.valFromOption(message) : "Hello ReScript!"
      });
}

export {
  $$default ,
  $$default as default,
}
/* No side effect */
