// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement("title", undefined, "NextJS X ReScript"), React.createElement("meta", {
                  content: "width=device-width, initial-scale=1",
                  name: "viewport"
                }), React.createElement("link", {
                  href: "/favicon.ico",
                  rel: "icon"
                }));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
