// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import 'styles/tailwind.css'
;

function $$default(props) {
  return React.createElement("html", undefined, React.createElement("head", undefined), React.createElement("body", undefined, props.children));
}

export {
  $$default ,
  $$default as default,
}
/*  Not a pure module */
