// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "px-4 py-8 container mx-auto"
            }, "ReScript X NextJS");
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
